import {
  Radio,
  Wrench,
  Headphones,
  Shield,
  Zap,
  Globe,
  BarChart2,
  TowerControl,
  Building2,
  Presentation,
  Monitor,
  BookOpen,
  Award,
} from "lucide-react";

export const iconMap: Record<string, React.FC<{ className?: string }>> = {
  Radio: ({ className }) => <Radio className={className} />,
  Wrench: ({ className }) => <Wrench className={className} />,
  Headphones: ({ className }) => <Headphones className={className} />,
  Shield: ({ className }) => <Shield className={className} />,
  Zap: ({ className }) => <Zap className={className} />,
  Globe: ({ className }) => <Globe className={className} />,
  BarChart2: ({ className }) => <BarChart2 className={className} />,
  TowerControl: ({ className }) => <TowerControl className={className} />,
  Building2: ({ className }) => <Building2 className={className} />,
  Presentation: ({ className }) => <Presentation className={className} />,
  Monitor: ({ className }) => <Monitor className={className} />,
  BookOpen: ({ className }) => <BookOpen className={className} />,
  Award: ({ className }) => <Award className={className} />,
};
